#ifndef _setting_html_
#define _setting_html_

const char html[] PROGMEM = "<!DOCTYPE html>"
                            "< html lang = 'en' >"
                            " < head >"
                            " < meta charset = 'utf -8 '>"
                            "<title > {title}</ title>"
                            " < meta charset = 'UTF-8' >"
                            " < meta name = 'viewport' content = 'width=device-width, initial-scale=1.0' >"
                            "< / head >"
                            " < body >"
                            " < div class= 'main' > "
                            "< h1 >{title}</ h1><br>"
                            " < form name = 'wificonfig' action = '/' method = 'POST' >"
                            " < div class = 'bb' > WiFi名称 : </ div><br> "
                            "< input class = 'input' type = 'text' value = '{ssid}' placeholder = '输入WiFi名称' name = 'ssid' > <br><br> "
                            "< div class = 'bb' >  WiFi密码 : </ div><br>"
                            " < input class = 'input' type = 'password' value = '{pwd}' placeholder = '输入WiFi密码' name = 'password' > <br><br> "
                            "  < div class = 'bb' >点灯密钥 : </ div><br> "
                            " < input class = 'input' type = 'text' value = '{auth}' placeholder = '输入点灯密钥' name = 'authkey' > <br><br><br><br> "
                            "< input style = 'font-weight:bold ;font-size:x-large;' class= 'input' type = 'submit' value = '配网' > "
                            " < / form >< / div ></ body>"
                            "< style > html,body{ width:100 % ; height:100 % ; margin:0; padding:0;}"
                            " .main{ width:100 % ; height:100 % ; margin:0; padding:0; text - align : center; font - weight : bold;}"
                            " .input{ resize:  none;outline:  none;margin: 4px auto;height:  45px;width:  80 % ;border: 1px solid #d0d1ce; padding - left : 15px; font - size : 14px; color:# 000; margin - left : 10px; border - radius : 10px; border : 1px solid #dcdfe6; background - color : #ffffff; } "
                            " .bb{ width:  80 % ; margin:  0px auto;  text - align : left; padding - left : 2px;height:  0px;  font - weight : bold;}"
                            "< / style >< / html > ";